### ISSUE TITLE
Unknown port designation when using LV2 plugin

### ISSUE THREAD

**Issue by simonvanderveldt** [DISTRHO/Nekobi#3]
When adding the LV2 plugin for Nekobi to Carla-rack (both from current master) I get the following message/error in Carla-rack's log:

```
lv2_rdf_new("http://distrho.sf.net/plugins/Nekobi") - got unknown port designation 'http://lv2plug.in/ns/lv2core#enabled'
```

Can't really determine from the log line if this is a Carla or Nekobi bug. Seems like one of the two is out of date/doesn't support `enabled`?

**Comment by falkTX** [comment]
Fixed in https://github.com/falkTX/Carla/commit/10ebda31659b5c8996c535ad84c9dc23b0c47d3b

**Comment by simonvanderveldt** [comment]
Can confirm that this is now fixed, thanks again! :)
