### ISSUE TITLE
Please add the 'insatall' target

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/Nekobi#8]

**Comment by yurivict** [comment]
Currently it installs into bin/ in the build directory.

**Comment by falkTX** [comment]
install target is only going to be on the dpf-plugins repository.
I do not see a point to do it here, nor I want to.

**Comment by yurivict** [comment]
> I do not see a point to do it here, nor I want to.

I don't quite understand how ports are expected to install plugins into ```$PREFIX```.

Same problem with your Kars plugin.
