### ISSUE TITLE
nekobi hangs when usb controller changes octave

### ISSUE THREAD

**Issue by muziker** [DISTRHO/Nekobi#9]
I use a usb controller to interface with nekobi. Nekobi runs in carla, and the usb controller uses a2jmidid to send midi signals. Once i hit the octave button on my controller, nekobi hangs. Carla still functions, but that version of nekobi functions. I can add a second nekobi, but once i try to delete the first nekobi, all of carla hangs.

This version of nekobi i'm using is from tag v1.3.6 of the dpf-plugin

**Comment by muziker** [comment]
I've also written a pure data arp that feeds into nekobi. For some reason, if nekobi gets a large bunch of midi input whose duration overlaps each other, there's a cumulative effect to the length of time before inputs retrigger the synth. nekobi should allow retriggers after the volume of the output has reached zero.

**Comment by falkTX** [comment]
Fixed in 0e999f34e128a2f758f68da52dae827f40db648a
